### numpy array operations

In [1]:
import numpy as np


In [7]:
arr= np.array([1, 2, 3,4, 5, 6,7,8,9,10])
print("Basic slicing:",arr[2:7])
print("Slicing with step:", arr[1:8:2])
print("Slicing with negative step:", arr[8:2:-1])
print("Negative slicing:", arr[-3])

Basic slicing: [3 4 5 6 7]
Slicing with step: [2 4 6 8]
Slicing with negative step: [9 8 7 6 5 4]
Negative slicing: 8


In [13]:
arr_2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific element:", arr_2d[1, 2])  # Element at row 1, column 2
print("Entire row:", arr_2d[1, :])  # Entire row 1
print("Entire column:", arr_2d[:, 1])  # Entire column 1
print("Slicing rows and columns:", arr_2d[0:2, 1:3])  # Rows 0-1, columns 1-2

Specific element: 6
Entire row: [4 5 6]
Entire column: [2 5 8]
Slicing rows and columns: [[2 3]
 [5 6]]


### Sorting

In [23]:
unsorted_arr = np.array([3, 1, 4, 2,7,9,5,6,8,0])
print("Sorted array:",  np.sort(unsorted_arr))


arr_2d_unsorted= np.array([[3, 1, 4], [2, 7, 9], [5, 6, 8]])
print("Sorted 2D array:", np.sort(arr_2d_unsorted, axis=0))  # Sort each column-

Sorted array: [0 1 2 3 4 5 6 7 8 9]
Sorted 2D array: [[2 1 4]
 [3 6 8]
 [5 7 9]]


### Filtering

In [ ]:
numbers=np.array([1, 2, 3, 4, 5,6,7,8,9,10])
even_number =  numbers[numbers % 2 == 0]
print("Even numbers:", even_number)
odd_number = numbers[numbers % 2 != 0]
print("Odd numbers:", odd_number)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
even_2d = arr_2d[arr_2d % 2 == 0]
print("Even numbers in 2D array:", even_2d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
odd_2d = arr_2d[arr_2d % 2 != 0]
print("Odd numbers in 2D array:", odd_2d)





Even numbers: [ 2  4  6  8 10]
Odd numbers: [1 3 5 7 9]
Even numbers in 2D array: [2 4 6 8]
Odd numbers in 2D array: [1 3 5 7 9]
Even numbers in 2D array: [2 4 6 8]
Odd numbers in 2D array: [1 3 5 7 9]


## Filter with mask

In [ ]:
mask=numbers > 5
print("Mask for numbers > 5:", numbers[mask])
mask_2d = arr_2d > 5
print("Mask for 2D array > 5:", arr_2d[mask_2d])
mask_2d = arr_2d < 5
print("Mask for 2D array < 5:", arr_2d[mask_2d])

Mask for numbers > 5: [ 6  7  8  9 10]
Mask for 2D array > 5: [6 7 8 9]
Mask for 2D array < 5: [1 2 3 4]


### Fancing indexing vs np.where()


#### np.where() is used to give condition 

In [55]:
indices = np.array([0, 2, 4])
print("Elements at indices 0, 2, 4:", numbers[indices])
where_result = np.where(numbers > 5)
print("Indices where numbers > 5:", where_result[0])  # Returns indices of elements satisfying the condition


condition_array = np.where(numbers > 5,numbers*2, numbers)
print("Condition array for numbers > 5:", condition_array)  # Returns indices of elements satisfying the condition

if (condition_array > 10).any():
    print("There are elements greater than 10 in the condition array.")
else:
    print("No elements greater than 10 in the condition array.")

condition_array = np.where(numbers > 5, "True", "False")
print("Condition array with string values:", condition_array)  # Returns indices of elements satisfying the condition

Elements at indices 0, 2, 4: [1 3 5]
Indices where numbers > 5: [5 6 7 8 9]
Condition array for numbers > 5: [ 1  2  3  4  5 12 14 16 18 20]
There are elements greater than 10 in the condition array.
Condition array with string values: ['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Adding and removing data


In [ ]:
arr1= np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined_array = np.concatenate((arr1, arr2))
print("Combined array:", combined_array)  # Concatenates arr1 and arr2



Combined array: [1 2 3 4 5 6]


### Array compatibility

In [61]:
a= np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print("Compatibility check for concatenation:", np.concatenate((a, b, c)))  # Concatenates a, b, and c
print("Compatibility check for concatenation with 2D array:", a.shape==b.shape)

Compatibility check for concatenation: [1 2 3 4 5 6 7 8 9]
Compatibility check for concatenation with 2D array: True


In [65]:
original= np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
combined_with_row = np.vstack((original, new_row))
print("Combined with new row:", combined_with_row)  # Adds new_row as a new row to original

new_column = np.array([[7], [8], [9]])
combined_with_column = np.hstack((combined_with_row, new_column))
print("Combined with new column:", combined_with_column)  # Adds new_column as a new column to combined_with_row

Combined with new row: [[1 2]
 [3 4]
 [5 6]]
Combined with new column: [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [69]:
arr=np.array([1, 2,3,4,5])
deleted = np.delete(arr,2)  # Deletes the second row (index 1)
print("Array after deleting second row:", deleted)  # Displays the array after deletion

Array after deleting second row: [1 2 4 5]
