## Numpy array and basics
learn about numpy with chi aur code

In [10]:
%pip install numpy
import numpy as np
import time

Note: you may need to restart the kernel to use updated packages.


# #creating array from list


In [ ]:
arr_1d=np.array({1,2,3,4,5})
print("1D Array:",arr_1d)

!D Array {1, 2, 3, 4, 5}


In [5]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [7]:
py_list = [1,2,3]
print("Python list nultiplication:", py_list * 3)

Python list nultiplication: [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
np_array = np.array([1,2,3]) #element wise multiplication
print("Numpy array multiplication:", np_array * 3)

Numpy array multiplication: [3 6 9]


In [11]:
start=time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operation time:", time.time() - start)


 list operation time: 0.12227845191955566


In [12]:
start_time = time.time()
np_array = np.array([i*2 for i in range(1000000)])
print("Numpy operation time:", time.time() - start_time)

Numpy operation time: 0.29735803604125977


### creating array from scratch

In [18]:
zeros= np.zeros((3, 4))
print("Zeros Array:\n", zeros)

ones=np.ones((2, 3))
print("Ones Array:\n", ones)

full=np.full((2, 2), 7)
print("Full Array:\n", full)


random_array = np.random.random((2, 2))
print("Random Array:\n", random_array)



sequence = np.arange(0, 10, 2)
print("Sequence Array:", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.08365046 0.20546901]
 [0.02001925 0.66073578]]
Sequence Array: [0 2 4 6 8]


### Vector, Matrix and Tensorflow

In [21]:
vector = np.array([1, 2, 3])
print("Vector:", vector)

matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [23]:
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr) 
print("Array Shape:", arr.shape)  # Shape of the array
print("Array Size:", arr.size)    # Number of elements in the array 
print("Array Data Type:", arr.dtype)  # Data type of the array elements
print("Array Dimension:", arr.ndim)  # Number of dimensions of the array

Original Array: [1 2 3 4 5]
Array Shape: (5,)
Array Size: 5
Array Data Type: int64
Array Dimension: 1


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original Array :", arr)

reshaped=arr.reshape(3, 4)
print("Reshaped Array:\n", reshaped)


raveled = reshaped.ravel()
print("Raveled Array:", raveled)
#returns view instead of copy
flattened = reshaped.flatten()
print("Flattened Array:", flattened)
#returns copy

#transpose
transposed = reshaped.T
print("Transposed Array:\n", transposed)

Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
